name: 'Body Tag Extractor'
author: 'TheBurchBlog'
description: 'The goal is to replicate tags like `fixes:` but make those variables exposed to the other actions through environment variables.'
inputs:
  tag:
    description: 'The tag placed inside the Body of the Issue or Pull Request before the value is defined'
    required: false
    default: 'body-tag:'
  env-variable:
    description: 'The environment variable to map the tag value to'
    required: false
    default: 'body-tag'
  default-value:
    description: 'If the tag is not found, the default value to be provided'
    required: false
    default: null

outputs:
  tag-value:
    description: 'The Tag value assigned'

runs:
  using: "composite"
  steps:
    - name: Extract Tag
      env:
        CONTAINS_TAG : ${{contains(github.event.issue.body, inputs.tag)}}
        PARSE-TAGS : ${{inputs.default-value}}
      run: |
        TAGS=$(echo ${{ github.event.issue.body }} | grep -Po "(?<=${{inputs.tag}}\s)(\w+)")
        echo $TAGS
        TAG_ARRAY=($TAG)
        echo $TAG_ARRAY
        echo "PARSE-TAGS=${TAGS_ARRAY[0]}" >> $GITHUB_ENV
      shell: bash

    - name: Setting Tag
      run: echo "${{env.PARSE-TAGS}}"
      shell: bash

    - name: Apply Tag
      run: echo "${{inputs.env-variable}}=${{env.PARSE-TAGS}}" >> $GITHUB_ENV
      shell: bash

