name: 'Body Tag Extractor'
author: 'TheBurchBlog'
description: 'The goal is to utilize tags like `fixes:` and expose the values through environment variables.'
branding:
  icon: 'search'
  color: 'blue'

inputs:
  tag:
    description: 'The tag placed inside the Body of the Issue or Pull Request before the value is defined'
    required: false
    default: 'body-tag:'
  env-variable:
    description: 'The environment variable to map the tag value to'
    required: false
    default: 'body-tag'
  default-value:
    description: 'If the tag is not found, the default value to be provided'
    required: false
    default: null
  tag-position:
    description: 'If multiple tags are found, which tag position should be returned (-1 = last). If tag position is higher than found, the default value is provided' 
    required: false
    default: -1

runs:
  using: "composite"
  env:
    BODY: ""
  steps:
    - name: Extract Issue Tag
      runs:
        using: 'node12'
        main: 'index.js'

