name: 'Body Tag Extractor'
author: 'TheBurchBlog'
description: 'The goal is to replicate tags like `fixes:` but make those variables exposed to the other actions through environment variables.'
inputs:
  tag:
    description: 'The tag placed inside the Body of the Issue or Pull Request before the value is defined'
    required: false
    default: 'body-tag:'
  env-variable:
    description: 'The environment variable to map the tag value to'
    required: false
    default: 'body-tag'
  default-value:
    description: 'If the tag is not found, the default value to be provided'
    required: false
    default: null
  tag-position:
    description: 'If multiple tags are found, which tag position should be returned (-1 = last)'
    required: false
    default: 0

outputs:
  tag-value:
    description: 'The Tag value assigned'

runs:
  using: "composite"
  steps:
    - name: Extract Tag
      env:
        CONTAINS_TAG : ${{contains(github.event.issue.body, inputs.tag)}}
      run: |
        RETURN_TAG=${{inputs.default-value}}
        if $CONTAINS_TAG
        then
          TAGS=$(echo ${{ github.event.issue.body }} | grep -Po "(?<=${{inputs.tag}}\s)(\w+)")
          echo $TAGS  
          i=0    
          for tag in $TAGS
          do
            echo "Loop $i $tag"
            if [[ "${{inputs.tag-position}}" -eq -1 ]]
            then
              RETURN_TAG=$tag
            elif [[ ${{inputs.tag-position}} -eq $i ]]
            then
              RETURN_TAG=$tag
              break
            fi
            i=$((i+1))
          done
        fi
        echo "${{inputs.env-variable}}=$RETURN_TAG" >> $GITHUB_ENV
      shell: bash

