name: Issue-Actions

on: issues

jobs:
  Test_Action:
    runs-on: ubuntu-latest
    env:
      MY_TAG: 'nope'

    name: Test Local Action
    steps:
      - uses: actions/checkout@v2

      - name: Run Action
        uses: ./
        with:
          tag: 'body-tag:'
          env-variable: 'MY_TAG'
          default-value: 'missing'

      - name: Test
        shell: bash
        run: echo "${{env.MY_TAG}}"

